### ISSUE TITLE
Testling badge.

### ISSUE THREAD

**Issue by mcollina** [Level/level-browserify#2]

**Comment by ralphtheninja** [comment]
@vweevers Should we use `airtap` for this as well?

**Comment by vweevers** [comment]
Might be overkill. We already have `level-js`, `abstract-leveldown`, `levelup` covered, and `level-packager` is planned.

**Comment by vweevers** [comment]
We could copy the browser matrix though.

**Comment by vweevers** [comment]
Oh I forgot that we intend to move some tests here, so in that case, yes, let's add airtap here as well.
