### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-browserify#52]

**Comment by ralphtheninja** [comment]
@vweevers Do you think there is any idea to wait a bit further with this?

**Comment by ralphtheninja** [comment]
Once this is out, we could start working on merging `level` and `level-browserify`.

**Comment by vweevers** [comment]
> Do you think there is any idea to wait a bit further with this?

We don't have a stable `level-js` yet.

**Comment by ralphtheninja** [comment]
> We don't have a stable level-js yet.

Yes, I just remember that when walking the dog.
